language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
env:
        - 17.0-rc2
        - R16B03
        - R16B02
        - R16B01
        - R16B
        - R15B03
        - R15B02
        - R15B01
        - R15B
        - R14B04
        - R14B03
        - R14B02
